repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        language: golang
        entry: golangci-lint run --config .golangci.yml --skip-dirs vendor
        types: [go]