name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: test
        run: go test -v -timeout=120s -covermode=count -coverprofile=profile.cov ./...
        env:
          GOFLAGS: "-mod=vendor"

      - name: race test
        run: go test -race -mod=vendor -timeout=120s -count=1 ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: --config .golangci.yml


      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: profile.cov
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
