name: Build and Push on Release

on:
  release:
    types:
      - created 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      env:
        IMAGE_NAME: mockster
        TAG: ${{ github.event.release.tag_name }}
      run: |
        docker build -t $IMAGE_NAME .
        docker tag $IMAGE_NAME ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$TAG
        docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$TAG
